name: samtools_get_contifs
description: Get a list of contigs from a bam file
keywords:
  - vcf
  - filter
tools:
  - samtools:
      description: |
        SAMtools is a set of utilities for interacting with and post-processing
        short DNA sequence read alignments in the SAM, BAM and CRAM formats, written by Heng Li.
        These files are generated as output by short read aligners like BWA.
      homepage: http://www.htslib.org/
      documentation: http://www.htslib.org/doc/samtools.html
      doi: 10.1093/bioinformatics/btp352
      licence: ["MIT"]
input:
  - meta:
      type: map
      description: |
        Groovy Map containing sample information
        e.g. [ id:'test']
  - bam:
      type: path
      description: Bam file of sample
      pattern: "*.bam"
  - bam_index:
      type: path
      description: Index of bam file
      pattern: "*.bam.bai"
output:
  - contigs:
      type: path
      description: Text file with list of contigs, one per line
      pattern: "contigs.txt"
  - versions:
      type: path
      description: File containing software versions
      pattern: "versions.yml"
authors:
  - "@mikesauria"